<!DOCTYPE html>
<html lang="en"><head>
<script src="topics_files/libs/clipboard/clipboard.min.js"></script>
<script src="topics_files/libs/quarto-html/tabby.min.js"></script>
<script src="topics_files/libs/quarto-html/popper.min.js"></script>
<script src="topics_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="topics_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="topics_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="topics_files/libs/quarto-html/quarto-syntax-highlighting-49e51e44f424ea8c7044b429bdbbbfe2.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.28">

  <meta name="author" content="Dimitri Dubois">
  <title>Common Pool Resources</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="topics_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="topics_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="topics_files/libs/revealjs/dist/theme/quarto-2740581606dc327e82f18f789b69d8a0.css">
  <link rel="stylesheet" href="ceem-slides.css">
  <link href="topics_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="topics_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="topics_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="topics_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Common Pool Resources</h1>
  <p class="subtitle">Static, Dynamic, Intergenerational and Spatial Perspectives</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Dimitri Dubois 
</div>
        <p class="quarto-title-affiliation">
            CEE-M, Univ. Montpellier, CNRS, INRAE, Institut Agro
          </p>
    </div>
</div>

</section>
<section>
<section id="content" class="title-slide slide level1 center">
<h1>Content</h1>

</section>
<section id="table-of-content-12" class="slide level2">
<h2>Table of content (1/2)</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong><a href="#/static-common-pool-resource">Static CPR</a></strong></p>
<ul>
<li><a href="#/the-game">The Game</a></li>
<li><a href="#/voluntary-information-sharing">Voluntary Information Sharing</a></li>
<li><a href="#/quality-of-relationships-within-groups">Quality of Relationships within groups</a></li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong><a href="#/dynamic-common-pool-resource">Dynamic CPR</a></strong></p>
<ul>
<li><a href="#/theoretical-model">Theoretical Model</a></li>
<li><a href="#/implementation-in-the-lab">Implementation in the lab</a></li>
<li><a href="#/continuous-vs-discrete-time">Continuous vs.&nbsp;discrete time</a></li>
<li><a href="#/impact-of-discounting-reference-periods">Impact of discounting reference periods</a></li>
<li><a href="#/individual-and-strategic-behaviors">Individual and strategic behaviors</a></li>
</ul>
</div></div>
</section>
<section id="table-of-content-22" class="slide level2">
<h2>Table of content (2/2)</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong><a href="#/intergenerational-management-of-common-pool-resources">Intergenerational CPR</a></strong></p>
<ul>
<li><a href="#/the-intergenerational-goods-game-igg">The Intergenerational Goods Game (IGG)</a></li>
<li><a href="#/intragenerational-conflict-undermines-cooperation-with-the-future">Intragenerational vs.&nbsp;intergenerational social dilemma</a></li>
<li><a href="#/legacy-or-lineage-framing-the-future-for-sustainability">Framing the future for sustainability</a></li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong><a href="#/dynamic-common-pool-resource-with-spatial-externalities">Dynamic CPR with Spatial Externalities</a></strong></p>
<ul>
<li><a href="#/theoretical-benchmark">Theoretical Benchmark</a></li>
<li><a href="#/spatial-externalities-and-collective-action">Spatial Externalities and Collective Action</a></li>
<li><a href="#/property-rights-and-productivity">Property Rights and Productivity</a></li>
</ul>
</div></div>
</section>
<section id="appendix" class="slide level2">
<h2>Appendix</h2>
<ul>
<li><a href="#/a-dynamic-cpr---maximization-problems">Dynamic CPR - Maximization Problems</a></li>
<li><a href="#/b-the-exponential-function-in-discounting">The exponential function in discounting?</a></li>
</ul>
</section>
<section class="slide level2">

<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/topics.png"></p>
<figcaption>QR Code to the slides</figcaption>
</figure>
</div>
<p>🌐 <a href="https://www.duboishome.info/dimitri/cours/topics" class="uri">https://www.duboishome.info/dimitri/cours/topics</a></p>
<!---------------------------------------------------------------------------->
</section></section>
<section>
<section id="introduction" class="title-slide slide level1 center">
<h1>Introduction</h1>

</section>
<section id="goods-classification" class="slide level2">
<h2>Goods classification</h2>
<p>Depends on two characteristics: <strong>Rivalry</strong> and <strong>Excludability</strong>.</p>
<ul>
<li><strong>Private Goods</strong>: Both excludable and rival, meaning people can be excluded from using them, and one person’s use diminishes availability for others.</li>
<li><strong>Club Goods</strong>: Excludable but non-rival, allowing limited access without overuse issues.</li>
<li><strong>Public Goods</strong>: Neither excludable nor rival, accessible to everyone without reducing availability.</li>
<li><strong>Common Pool Resources</strong>: Non-excludable but rival, making them susceptible to overuse and depletion.</li>
</ul>
</section>
<section class="slide level2">

<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Type of Good</th>
<th>Rivalry</th>
<th>Excludability</th>
<th>Examples</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Private Goods</strong></td>
<td>High</td>
<td>High</td>
<td>Food, clothing, personal devices</td>
</tr>
<tr class="even">
<td><strong>Club Goods</strong></td>
<td>Low</td>
<td>High</td>
<td>Cinemas, private parks, toll roads</td>
</tr>
<tr class="odd">
<td><strong>Public Goods</strong></td>
<td>Low</td>
<td>Low</td>
<td>National defense, air, public parks</td>
</tr>
<tr class="even">
<td><strong>Common Pool Resources</strong></td>
<td>High</td>
<td>Low</td>
<td>Fisheries, groundwater, forests</td>
</tr>
</tbody>
</table>
</section>
<section id="common-pool-resources-cprs" class="slide level2">
<h2>Common Pool Resources (CPRs)</h2>
<ul>
<li>CPRs are subject to the <strong>Tragedy of the Commons</strong> (Hardin 1968), that leads to over-extraction and depletion of the resource.</li>
<li>Individuals acting in their <strong>own self-interest</strong> can lead to collective ruin, as each user has an incentive to extract as much as possible, disregarding the long-term sustainability of the resource.</li>
<li>This tragedy is not inevitable, as shown by <strong>Ostrom</strong>’s work on economic governance of the commons.</li>
</ul>
<div title="Note">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Behavioral and experimental economists have also made contributions and found mechanisms that can help to mitigate the tragedy and reduce the over-exploitation, like <strong>communication, sanctions, property rights, regulation/quotas or nudges</strong>.</p>
</div>
</div>
</div>
</div>
</section>
<section id="cpr-model" class="slide level2">
<h2>CPR Model</h2>
<ul>
<li>The basic CPR model involves a <strong>group of individuals who have access to a shared resource</strong>.</li>
<li>Each individual can choose <strong>how much of the resource to extract</strong>, but the total extraction by all individuals affects the overall availability of the resource.</li>
<li>The model typically includes a <strong>payoff function</strong> that captures the benefits and costs associated with extraction.</li>
<li><em>The goal is to understand how individuals make decisions about extraction and how these decisions impact the sustainability of the resource over time</em>.</li>
</ul>
</section></section>
<section>
<section id="static-common-pool-resource" class="title-slide slide level1 center">
<h1>Static Common Pool Resource</h1>

</section>
<section id="the-game" class="slide level2">
<h2>The Game</h2>
<p><em>Walker, Herr, Gardner &amp; Ostrom (2000)</em></p>
<ul>
<li><strong>Variables</strong>:
<ul>
<li><span class="math inline">\(x_i\)</span>: Individual extraction</li>
<li><span class="math inline">\(X = \sum_{j=1}^n x_j\)</span>: Total group extraction</li>
</ul></li>
<li><strong>Benefit Function</strong>:
<ul>
<li><span class="math inline">\(B_i(x_i) = a x_i - b x_i^2\)</span>
<ul>
<li><span class="math inline">\(a\)</span>: Initial benefit per unit extracted</li>
<li><span class="math inline">\(b\)</span>: Diminishing returns parameter</li>
</ul></li>
</ul></li>
</ul>
</section>
<section class="slide level2">

<ul>
<li><strong>Cost Function</strong>:
<ul>
<li><span class="math inline">\(C_i(x_i, X) = x_i (c + kX)\)</span>
<ul>
<li><span class="math inline">\(c\)</span>: Base cost of extraction</li>
<li><span class="math inline">\(k\)</span>: Marginal cost linked to total extraction (captures negative externality)</li>
</ul></li>
</ul></li>
<li><strong>Individual Payoff</strong>: <span class="math display">\[
\pi_i(x_i, X) = a x_i - b x_i^2 - x_i(c + k X)
\]</span></li>
</ul>
<blockquote>
<p><em>Each player chooses <span class="math inline">\(x_i\)</span> to maximize their own payoff, but total extraction <span class="math inline">\(X\)</span> increases costs for everyone, creating a social dilemma.</em></p>
</blockquote>
</section>
<section class="slide level2">

<h3 id="nash-equilibrium">Nash Equilibrium</h3>
<p>Each player maximizes their own payoff given the others’ decisions: <span class="math display">\[
\max_{x_i} \ \pi_i(x_i, X_{-i}) = a x_i - b x_i^2 - x_i (c + kX)
\]</span></p>
<p>where <span class="math inline">\(X = x_i + X_{-i}\)</span></p>
<p>First-order condition (FOC): <span class="math inline">\(a - 2b x_i - c - kX = 0\)</span></p>
<p>Assuming symmetry <span class="math inline">\(x_i = x\)</span>, <span class="math inline">\(X = nx\)</span>: <span class="math display">\[
x_i^{Nash} = \frac{a - c}{2b + k(n+1)}
\]</span></p>
</section>
<section class="slide level2">

<h3 id="social-optimum">Social Optimum</h3>
<p>Maximize total group payoff <span class="math inline">\(\Pi = \sum_{i=1}^n \pi_i\)</span></p>
<p><span class="math inline">\(\max_{x_1, \dots, x_n} \ \sum_{i=1}^{n} \left(a x_i - b x_i^2 - x_i (c + kX)\right)\)</span></p>
<p>Under symmetry <span class="math inline">\(x_i = x\)</span>, <span class="math inline">\(X = nx\)</span>, becomes: <span class="math display">\[
\max_{x} \ n\left(a x - b x^2 - x(c + knx)\right)
\]</span></p>
<p>FOC: <span class="math inline">\(a - 2b x - c - 2knx = 0\)</span> <span class="math display">\[
x_i^{Social} = \frac{a - c}{2b + 2kn}
\]</span></p>
</section>
<section class="slide level2">

<ul>
<li><em>NE</em>: players ignore the negative effect of their extraction on others.</li>
<li><em>SO</em>: players internalize the group-level externality and extract less.</li>
</ul>
</section>
<section class="slide level2">

<p>With <span class="math inline">\(a = 0.383\)</span>, <span class="math inline">\(b = 0.001\)</span>, <span class="math inline">\(c = 0.005\)</span>, <span class="math inline">\(k = 0.005\)</span>, <span class="math inline">\(n = 4\)</span>: - <span class="math inline">\(x_i^{Nash} \approx 14\)</span> tokens - <span class="math inline">\(x_i^{Social} \approx 9\)</span> tokens</p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/walker_graph.png" height="400"></p>
<figcaption>Theoretical Paths</figcaption>
</figure>
</div>
</section>
<section id="voluntary-information-sharing" class="slide level2">
<h2>Voluntary Information Sharing</h2>
<p>Dubois, D., Farolfi, S., Rouchier, J. &amp; Nguyen Van, P., 2020. “<a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0240212">Contrasting effects of information sharing on CPR extraction behaviour: experimental findings</a>”. Plos One 15 (10): e0241212.</p>
</section>
<section class="slide level2">

<ul>
<li><strong>Social information</strong> — the information available to participants about others’ actions — is crucial for common resource management.</li>
<li>Most participants are <strong>conditional cooperators</strong> (Fischbacher et al.&nbsp;2001), highlighting the potential influence of social information on cooperative behavior.</li>
<li><strong>Aggregate information</strong> about group decisions has been shown to increase contributions in public goods games. Adding <strong>individual (anonymous) contributions</strong> can further boost cooperation (Sell &amp; Wilson, 1991).</li>
</ul>
</section>
<section class="slide level2">

<ul>
<li>However, detailed information about others’ actions can decrease cooperation, as it may reveal <strong>free riders</strong> within the group (Nikiforakis, 2010; Villena &amp; Zecchetto, 2010).</li>
<li><strong>Mixed impact of social information</strong>: While some forms enhance cooperation, others can undermine it by exposing non-cooperative behavior.</li>
<li><strong>Modern connected devices and social networks</strong> facilitate information exchange, enabling real-time sharing of consumption and resource extraction data.</li>
</ul>
</section>
<section class="slide level2">

<h3 id="research-question">Research question</h3>
<p><strong><em>Investigate the impact of social information through voluntary sharing mechanisms on cooperative behavior in common-pool resources.</em></strong></p>
</section>
<section class="slide level2">

<p>Two Mechanisms of Information Sharing: - <strong>Voluntary Disclosure (VD)</strong>: Stakeholders choose whether to disclose their extraction level. - <strong>Free Disclosure (FD)</strong>: Stakeholders choose whether to disclose <em>and can determine the extraction level they display</em> (which may differ from the actual level).</p>
</section>
<section class="slide level2">

<h3 id="a-simplified-cpr-game">A Simplified CPR Game</h3>
<ul>
<li><p><span class="math inline">\(4\)</span> players and a shared resource of <span class="math inline">\(40\)</span> tokens.</p></li>
<li><p>Each player <span class="math inline">\(i\)</span> chooses an extraction level <span class="math inline">\(x_i \in [0, 10]\)</span>.</p></li>
<li><p><strong>Individual payoff function</strong>: <span class="math inline">\(\pi_i(x_i, X) = 3x_i - 0.01875 \cdot X^2\)</span> where <span class="math inline">\(X = \sum_{j=1}^4 x_j\)</span> is the total group extraction.</p></li>
<li><p><strong>Key features</strong>:</p>
<ul>
<li>The benefit is linear.</li>
<li>The cost is quadratic and shared.</li>
<li>The externality is global and symmetric.</li>
</ul></li>
</ul>
</section>
<section class="slide level2">

<ul>
<li><strong>Dominant strategy</strong>:
<ul>
<li>Each player maximizes own payoff by choosing the maximum <span class="math inline">\(x_i = 10\)</span> (Nash equilibrium).</li>
</ul></li>
<li><strong>Social optimum</strong>:
<ul>
<li>Total group payoff is maximized when <span class="math inline">\(X = 20\)</span>, i.e.&nbsp;<span class="math inline">\(x_i = 5\)</span> for each player.</li>
</ul></li>
</ul>
<blockquote>
<p>Captures the essence of CPR dilemmas: Private incentives lead to overuse, while collective interest requires restraint.</p>
</blockquote>
</section>
<section class="slide level2">

<h3 id="experimental-design">Experimental Design</h3>
<ul>
<li>CPR game played <strong>20 rounds</strong> in fixed <strong>groups of 4</strong> participants.</li>
<li>3 treatments, following a between-subject design:
<ul>
<li><strong><em>Mandatory Disclosure (MD)</em></strong>: individual extractions are disclosed in an automatic and mandatory manner</li>
<li><strong><em>Voluntary Disclosure (VD)</em></strong>: after making their extraction decision, the players have to decide whether or not they wish to make this extraction decision public</li>
<li><strong><em>Free Disclosure (FD)</em></strong>: after making their extraction decision, players have to decide whether or not they wish to make their extraction level public, as well as additionally deciding the amount of extraction they wish to publicize</li>
</ul></li>
</ul>
</section>
<section class="slide level2">

<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>MD</th>
<th>VD</th>
<th>FD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Voluntary sharing</strong></td>
<td>No</td>
<td>Yes</td>
<td>Yes</td>
</tr>
<tr class="even">
<td><strong>Freedom to choose the value to be disclosed</strong></td>
<td>No</td>
<td>No</td>
<td>Yes</td>
</tr>
</tbody>
</table>
</section>
<section class="slide level2">

<h3 id="conjectures">Conjectures</h3>
<p><strong>Conjecture 1</strong>: Individuals disclose extractions frequently due to: - Desire to signal cooperation (warm-glow effect). - Perception of a “socially appropriate” extraction level and descriptive norm.</p>
<p><strong>Conjecture 2 (Voluntary Disclosure)</strong>: 1. <strong>Disclosed extractions</strong> &lt; <strong>Non-disclosed extractions</strong>. 2. <strong>Average extractions</strong> &lt; <strong>Mandatory Disclosure</strong>. - Non-cooperators avoid making extractions public to limit influence on others. - Guilt or shame can deter non-prosocial behavior.</p>
</section>
<section class="slide level2">

<p><strong>Conjecture 3 (Free Disclosure)</strong>: 1. <strong>Disclosed extractions</strong> &lt; <strong>Non-disclosed extractions</strong>. 2. <strong>Disclosed extractions</strong> &lt; <strong>Actual extractions</strong>. 3. <strong>Average extractions</strong> &lt; <strong>Mandatory Disclosure</strong>. - Cooperators likely to disclose accurate extractions; non-cooperators may hide actual values. - Some may signal optimal extractions to set a group norm. - Strategic false disclosures may erode trust, hindering norm formation and conditional cooperation.</p>
</section>
<section class="slide level2">

<h3 id="results">Results</h3>
<h4 id="average-extraction">Average extraction</h4>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/info_sharing/extraction_evolution.png" height="450"></p>
<figcaption>Extraction evolution</figcaption>
</figure>
</div>
</section>
<section class="slide level2">

<p><strong>Information sharing is effective in reducing extraction</strong>:</p>
<ul>
<li>Average extractions in MD significantly higher than in VD and FD</li>
<li>No significant difference between VD and FD</li>
</ul>
</section>
<section class="slide level2">

<h4 id="effect-of-disclosure">Effect of Disclosure</h4>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/info_sharing/extraction_display_extraction.png" height="500"></p>
<figcaption>Extraction disclosure</figcaption>
</figure>
</div>
</section>
<section class="slide level2">

<ul>
<li><strong><em>Players who disclosed their extraction decision extracted less than non-disclosers</em></strong>.</li>
<li><strong>VD Treatment</strong>:
<ul>
<li>Overall average and average of disclosed extractions (displayed values) are closely aligned.</li>
<li>This alignment supports expected effects of social information: imitation, convergence of decisions, and norm formation within groups.</li>
</ul></li>
<li><strong>FD Treatment</strong>:
<ul>
<li>A significant discrepancy between average displayed extractions and actual extractions.</li>
</ul></li>
</ul>
</section>
<section class="slide level2">

<h4 id="strategic-misreporting-in-the-fd-treatment">Strategic Misreporting in the FD Treatment</h4>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/info_sharing/fd_treatment.png" height="500"></p>
<figcaption>FD treatment</figcaption>
</figure>
</div>
</section>
<section class="slide level2">

<ul>
<li><p><strong>Strategic Misreporting</strong>: Players who misrepresented their extraction level extracted significantly more than those who reported their actual extraction or chose not to disclose.</p></li>
<li><p><strong>Understanding of Social Optimum</strong>: These players appeared to recognize the social optimum (5 units) as a target extraction level.</p></li>
<li><p><strong>Emergence of Strategic Behavior</strong>:</p>
<ul>
<li>The freedom to selectively disclose favored strategic reporting.</li>
<li>Players sent misleading signals by reporting extractions near the social optimum, anticipating that others might reduce their own extraction, thus allowing the misreporters to maximize their profit.</li>
</ul></li>
</ul>
</section>
<section class="slide level2">

<h3 id="findings-and-implications">Findings and implications</h3>
<p><strong>Effects of social information are mixed</strong>:</p>
<ul>
<li><strong>Voluntary Disclosure</strong>: Tends to <strong>encourage cooperative actions</strong> and more sustainable resource use. Cooperative players disclose their actions, while less cooperative players often choose not to disclose to avoid influencing others negatively. This <strong>selective disclosure can foster a cooperative norm</strong> by highlighting lower extractions without spreading non-cooperative behavior.</li>
<li><strong>Free Disclosure</strong>: Allows <strong>strategic manipulation</strong> of shared information. Less cooperative players can misrepresent their extractions, signaling a low, socially optimal level, while actually extracting more. This behavior can erode trust, hinder the formation of a social norm, and potentially hasten resource depletion.</li>
</ul>
</section>
<section class="slide level2">

<p><strong>Implications</strong>:</p>
<ul>
<li>Voluntary disclosure can help align actions with cooperative norms when individuals selectively disclose honest information.</li>
<li>Free disclosure, however, may undermine group trust and lead to over-exploitation, as selective false reporting can mislead others and disrupt cooperative intentions within the group.</li>
</ul>
</section>
<section id="quality-of-relationships-within-groups" class="slide level2">
<h2>Quality of Relationships within groups</h2>
<p>Brugnach, M., Dubois, D. &amp; Farolfi, S.,“The Power of Bonds: How the Quality of Relationships Within a Group Can Drive Collective Actions in Common Pool Resource Management”</p>
</section>
<section class="slide level2">

<h3 id="research-question-1">Research question</h3>
<p><strong><em>Does the quality of relationships within a group impact collective management of common pool resources (CPRs)?</em></strong></p>
<ul>
<li>Relationships shape collective actions in social dilemmas.</li>
<li>Managing CPRs benefits from cooperative actions which could be influenced by social ties and relational quality.</li>
</ul>
<blockquote>
<p>Strong, positive relationships within a group are likely to foster cooperation and responsible resource extraction.</p>
</blockquote>
</section>
<section class="slide level2">

<h3 id="challenge-building-relationships-within-a-group-in-the-lab">Challenge: building relationships within a group in the Lab</h3>
<p>We developed an <strong>effort task</strong> (counting ones in 10x10 grids of zeros and ones) with three different payoff schemes to shape relational quality:</p>
<ul>
<li><strong>Individualistic</strong> (control treatment): Each player is paid based on their own performance.</li>
<li><strong>Cooperative</strong> (promotes positive relational quality): Each player is paid based on the best performance within the group.</li>
<li><strong>Competitive</strong> (likely reduces relational quality): Only the player with the highest performance is paid; others receive nothing.</li>
</ul>
</section>
<section class="slide level2">

<p>In all three conditions: - Players shared <strong>the same 100 grids</strong>, displayed upon clicking numbers from 1 to 100. - <strong>Communication was allowed</strong> in each condition. - The task had a duration of <strong>3 minutes</strong>.</p>
</section>
<section class="slide level2">

<p><strong>The effort task</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/relationships/effort_task.png" height="500"></p>
<figcaption>Effort task</figcaption>
</figure>
</div>
</section>
<section class="slide level2">

<h3 id="cpr-game">CPR Game</h3>
<p><strong>Walker, Herr, Gardner, and Ostrom (2000)</strong>’s game for 4 players, repeated for 10 rounds.</p>
<ul>
<li>NE: 14 tokens<br>
</li>
<li>SO: 9 tokens</li>
<li>Conditions:
<ul>
<li><strong>Without Communication</strong><br>
</li>
<li><strong>With Pre-Play Communication</strong>: 3 minutes of chat before the first round.</li>
</ul></li>
</ul>
</section>
<section class="slide level2">

<h3 id="questionnaire-on-relational-quality">Questionnaire on Relational Quality</h3>
<p>To evaluate <strong>relational quality</strong> within groups, a detailed questionnaire was administered:</p>
<ul>
<li>Emotional Experience</li>
<li>Personal Feelings</li>
<li>Behavioral Attitudes:
<ul>
<li><em>Towards Others</em>: participants’ behaviors toward fellow group members.</li>
<li><em>Perceptions of Others</em>: participants’ views on others’ behaviors within the group.</li>
</ul></li>
<li>Closeness-to-Others: Using the <em>Inclusion of Other in Self (IOS)</em> scale (Gächter et al.&nbsp;2015) to assess perceived closeness within the group.</li>
</ul>
</section>
<section class="slide level2">

<p>Inclusion of Other in Self (IOS)</p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/relationships/ios.png" height="450"></p>
<figcaption>IOS</figcaption>
</figure>
</div>
</section>
<section class="slide level2">

<h3 id="experimental-design-and-hypotheses">Experimental design and hypotheses</h3>
<ul>
<li>Flow of the experiment: Effort task, questionnaires, CPR Game (10 rounds), Questionnaires.</li>
<li>Between-subject design</li>
<li>248 participants
<ul>
<li>88 in treatment Individualist (48 w/o comm. and 40 with)</li>
<li>80 in treatment Cooperation (44 w/o comm. and 36 with)</li>
<li>80 in treatment Competition (44 w/o comm. and 36 with)</li>
</ul></li>
</ul>
</section>
<section class="slide level2">

<p><strong><em>Hypotheses</em></strong> - H1 : <strong>Cooperative effort task enhances relational quality</strong>, while competitive task diminishes it. - H2: <strong>Higher relational quality leads to better management</strong> of CPRs; lower relational quality worsens CPR outcomes.</p>
</section>
<section class="slide level2">

<h3 id="results-1">Results</h3>
<h4 id="link-between-effort-task-and-responses-to-the-questionnaire">Link between effort task and responses to the questionnaire</h4>
<ol type="1">
<li><strong>PCA analysis</strong> to identify main components of the questionnaire (44 variables)
<ul>
<li>To reduce questionnaire responses into key components for understanding relational quality.</li>
<li>Top components reveal underlying factors.</li>
</ul></li>
</ol>
</section>
<section class="slide level2">

<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/relationships/topTenAxes.png" height="500"></p>
<figcaption>PCA top 10</figcaption>
</figure>
</div>
</section>
<section class="slide level2">

<p><strong>Players’ coordinates on main axes by treatment</strong></p>
<ul>
<li>Visualization of player distributions on principal axes based on treatment (Individualistic, Cooperative, Competitive).</li>
<li>Objective: To examine if the treatments correlate with distinct relational patterns identified in the PCA.</li>
</ul>
</section>
<section class="slide level2">

<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/relationships/players_on_axes.png" height="500"></p>
<figcaption>Players on axes</figcaption>
</figure>
</div>
</section>
<section class="slide level2">

<ol start="2" type="1">
<li><strong>K-Means clustering</strong> of questionnaire responses:
<ul>
<li>Identify distinct clusters of player experiences, recognizing that emotions and perceptions may vary by individual performance and group communication dynamics.</li>
<li>Elbow method and Silhouette score indicated 2 optimal clusters.</li>
</ul></li>
</ol>
</section>
<section class="slide level2">

<p><strong>Cluster Visualization on PCA Components</strong><br>
Player distributions by clusters across main PCA axes.</p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/relationships/clusters_participants.png"></p>
<figcaption>Cluster on PCA components</figcaption>
</figure>
</div>
</section>
<section class="slide level2">

<ul>
<li><strong>Cluster-0</strong>: Mostly cooperative task participants (59/124), with balanced individualist participants (41/88).</li>
<li><strong>Cluster-1</strong>: Primarily competitive task participants (56/124) and the remaining individualist participants (47/88).</li>
</ul>
</section>
<section class="slide level2">

<h4 id="impact-of-group-composition-on-cpr-management">Impact of Group Composition on CPR Management</h4>
<p>Analyze CPR extraction behavior in relation to <strong>group composition based on clusters</strong>.</p>
<p><strong>Group Composition Types</strong>: - Defined by <strong>cluster labels</strong> assigned to each participant (Cluster-0 or Cluster-1). - Each group (4 players) categorized into three types: - <strong>Maj. 0</strong>: Majority of Cluster-0 participants (26 groups) - <strong>Maj. 1</strong>: Majority of Cluster-1 participants (25 groups) - <strong>Mix</strong>: Equal representation of Cluster-0 and Cluster-1 (11 groups)</p>
<p>This classification allows us to study how <strong>relational quality</strong> impacts CPR management, testing hypothesis H2.</p>
</section>
<section class="slide level2">

<p><strong>Evolution of average CPR extraction depending on group composition</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/relationships/extraction_group_cluster_cat.png" height="500"></p>
<figcaption>Extraction group composition</figcaption>
</figure>
</div>
</section>
<section class="slide level2">

<h3 id="findings-and-implications-1">Findings and Implications</h3>
<ul>
<li>Developed an experimental mechanism to induce diverse relational qualities.</li>
<li>Group composition —based on clusters analysis— impacted CPR management more than treatments alone.</li>
<li>Communication notably reduced CPR extractions.</li>
</ul>
</section></section>
<section>
<section id="dynamic-common-pool-resource" class="title-slide slide level1 center">
<h1>Dynamic Common Pool Resource</h1>

</section>
<section class="slide level2">

<ul>
<li>CPRs have mainly been studied in a <strong>static framework</strong>: the resource is assumed to be fixed and unchanging over the course of the game. Players make decisions about how much to extract from the resource but theses decisions do not affect the future availability of the resource.</li>
<li>However in reality <strong>many CPRs are dynamic</strong> : they regenerate over an infinite horizon of time and the extraction decisions made by players can affect the future availability of the resource.</li>
</ul>
</section>
<section id="theoretical-model" class="slide level2">
<h2>Theoretical Model</h2>
<p>Based on <strong>Rubio &amp; Casino (2003)</strong></p>
<ul>
<li>Linear quadratic model in which two agents <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span> exploit a renewable resource <span class="math inline">\(H\)</span>, the resource can be assimilated to a groundwater</li>
<li>Extraction from the resource generates a revenue <span class="math inline">\(B(w) = aw -\frac{b}{2}w^2\)</span></li>
<li>Extraction has a cost <span class="math inline">\(C(H, w) = max(0, c_0-c_1H)w\)</span>
<ul>
<li>The cost depends negatively on the level of resource <span class="math inline">\(H\)</span></li>
<li>The cost is positive when the resource level is lower than <span class="math inline">\(\frac{c_0}{c_1}\)</span> and null if equal or higher. This a piecewise function to avoid subsidy in case of a high level of resource</li>
</ul></li>
</ul>
</section>
<section class="slide level2">

<p>In the infinite horizon, the total discounted payoff is given by</p>
<p><span class="math inline">\(\int_{0}^{\infty}e^{-rt} \left[ aw_i(t)-\frac{b}{2}w_i(t)^{2}-\max (0,\; c_{0}-c_{1}H(t))w_i(t) \right]dt\)</span></p>
<p>with <span class="math inline">\(\dot H(t)=R-\alpha(w_i(t)+w_j(t))\)</span></p>
<p><span class="math inline">\(e^{-rt}\)</span> is the discount factor (<span class="math inline">\(r\)</span> is the discount rate), <span class="math inline">\(R\)</span> is the natural recharge and <span class="math inline">\(\alpha\)</span> is the return flow coefficient.</p>
<p><strong>Each player’s extraction reduces the resource level, affecting not only their own future payoffs but also the other player’s future payoffs</strong>. This interdependence of decisions and outcomes, inherent in CPRs, is incorporated into this dynamic equation.</p>
</section>
<section class="slide level2">

<h3 id="theoretical-paths">Theoretical Paths</h3>
<p><strong>3 benchmarks</strong></p>
<ul>
<li><strong>Social optimum</strong>: both players in the pair maximize the joint discounted net payoffs and maintain the resource at an efficient level (cooperative solution)</li>
<li><strong>Feedback</strong>: players maximize their own discounted net payoffs, they adopt a non-cooperative strategy</li>
<li><strong>Myopic</strong>: at each instant players maximize their current payoff regardless of the evolution of the resource</li>
</ul>
</section>
<section class="slide level2">

<p>Choice of parameters such that theoretical paths are disctincts : <span class="math inline">\(H_0=15, R=0.56, a=2.5, b=1.8, c_0=2, c_1=0.1, r=0.005, \alpha=1\)</span></p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/profiles/theoretical_paths.png" height="500"></p>
<figcaption>Theoretical Paths</figcaption>
</figure>
</div>
</section>
<section id="implementation-in-the-lab" class="slide level2">
<h2>Implementation in the lab</h2>
<h3 id="time-in-the-lab">Time in the lab</h3>
<p><strong>Continuous time</strong> - Extractions can be made at any instant and the resource evolves continuously. - Strict continuous time is not feasible in the lab, it’s necessary to discretize the model with a small discretization rate.</p>
<p><strong>Discrete-time</strong></p>
<p>In discrete time, extractions are made at specific intervals and the resource evolves from one interval to the next.</p>
</section>
<section class="slide level2">

<h3 id="infinite-horizon-in-the-lab">Infinite Horizon in the lab</h3>
<ul>
<li>Incorporated into Players’ Payoff Calculations: Models long-term impact by combining cumulative and future payoffs:
<ul>
<li><em>Cumulative Discounted Payoff</em>: Sum of payoffs from <span class="math inline">\(t=0\)</span> to <span class="math inline">\(t=p\)</span>.</li>
<li><em>Future Discounted Payoff</em>: Projected payoff from <span class="math inline">\(t=p\)</span> to <span class="math inline">\(t=\infty\)</span> based on a steady extraction rate.</li>
</ul></li>
<li>Encourages players to consider sustainable extraction rates by making long-term consequences more salient.</li>
</ul>
</section>
<section id="continuous-vs.-discrete-time" class="slide level2">
<h2>Continuous vs.&nbsp;discrete time</h2>
<p>Djiguemde, M., Dubois, D., Sauquet, A. &amp; Tidball, M., 2022. “<a href="https://doi.org/10.1007/s10640-022-00700-2">Continuous Versus Discrete Time in Dynamic Common Pool Resource Game Experiments</a>”. Environmental and Resource Economics 82, pp.&nbsp;985-1014.</p>
</section>
<section class="slide level2">

<h3 id="research-question-2">Research question</h3>
<p><strong><em>Does the nature of time (continuous vs.&nbsp;discrete) affect behavior in a dynamic common pool resource game?</em></strong></p>
<blockquote>
<p><em>Theoretical models often assume continuous time for dynamic CPRs, but experiments typically use discrete time.</em></p>
</blockquote>
</section>
<section class="slide level2">

<ul>
<li>Two models, one in continuous time and one in discrete time, with similar theoretical paths.</li>
<li>Continuous-time (CT): discretization rate <span class="math inline">\(\tau=0.1\)</span></li>
<li>Discrete-time (DT): discretization rate <span class="math inline">\(\tau=1\)</span></li>
<li>A total <strong>play time of 10 minutes</strong> in both treatments:
<ul>
<li>CT: <strong>600 seconds</strong>, where 1 second = 0.1 instant in the model.</li>
<li>DT: <strong>60 periods</strong>, with 10 seconds per period → 1 period = 1 instant in the model.</li>
<li>Both treatments involved <strong>60 model instants</strong> of play.</li>
</ul></li>
</ul>
</section>
<section class="slide level2">

<h3 id="interface">Interface</h3>
<p>Continuous time <img data-src="img/cont_disc/screenshot_continuous.png" class="quarto-figure quarto-figure-center" height="500" alt="Continuous"></p>
</section>
<section class="slide level2">

<p>Discrete time <img data-src="img/cont_disc/screenshot_discrete.png" class="quarto-figure quarto-figure-center" height="500" alt="Discrete"></p>
</section>
<section class="slide level2">

<h3 id="experimental-design-1">Experimental Design</h3>
<ul>
<li>Between subject design</li>
<li>Two scenarios:
<ul>
<li>Optimal control (single player extracting from the resource)</li>
<li>Game (two players extracting from the same resource)</li>
</ul></li>
<li>A total of 392 participants.
<ul>
<li>Optimal control: 202 participants: 104 in CT and 98 in DT.</li>
<li>Game: 190 participants: 49 pairs in CT and 46 pairs in DT.</li>
</ul></li>
</ul>
</section>
<section class="slide level2">

<h3 id="results-2">Results</h3>
<p><em>Evolution of the average resource level over time</em></p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/cont_disc/cont_dis_results.png" height="480"></p>
<figcaption>Courbes résultat</figcaption>
</figure>
</div>
</section>
<section class="slide level2">

<ul>
<li>The resource increases in the optimal control (single player) scenario, but decreases as soon as strategic interaction is introduced.</li>
<li>The nature of time does not significantly affect player behavior in the optimal control scenario but does in the game scenario.</li>
</ul>
</section>
<section class="slide level2">

<p><strong>In the game</strong></p>
<ul>
<li>In the continuous-time treatment, <strong>players adjust their extraction rates more frequently and in smaller increments</strong> compared to the discrete-time treatment.</li>
<li>In the CT treatment, players were more likely to use a <strong><em>“tit-for-tat” strategy</em></strong>, where they would match the extraction rate of the other player. In the DT treatment, players were more likely to use a <strong><em>“best response” strategy</em></strong>, where they would adjust their extraction rate based on the other player’s previous extraction rate.</li>
<li>Final payoffs are <strong><em>more unequally distributed in the DT treatment</em></strong> compared to the CT treatment.</li>
</ul>
</section>
<section class="slide level2">

<h3 id="findings-and-implications-2">Findings and implications</h3>
<ul>
<li>The <strong><em>nature of time matters when the common pool resource is played with strategic interactions between stakeholders</em></strong>.</li>
<li>This study also makes a significant methodological contribution. We proposed a novel methodology for testing continuous-time models in a laboratory setting, despite the inherent discrete nature of such implementations. This approach allows for a more accurate representation of continuous-time dynamics and provides a framework for future experimental studies in this area.</li>
</ul>
</section>
<section id="impact-of-discounting-reference-periods" class="slide level2">
<h2>Impact of discounting reference periods</h2>
<p>Davin, M., Dubois, D., Erdlenbruch, K. &amp; Willinger, M., 2025. “<a href="https://doi.org/10.1016/j.reseneeco.2025.101531">Discounting and extraction behavior in continuous time resource experiments</a>”. Resource and Energy Economics 84.</p>
</section>
<section class="slide level2">

<h3 id="research-question-3">Research question</h3>
<p><strong><em>How different discounting periods affect behavior in a resource extraction experiment.</em></strong></p>
<p>In dynamic games, <strong>discounting is typically based on a reference period</strong>.</p>
<ul>
<li>Theory: discounting is done at <strong>time zero</strong>, where agents choose optimal paths.</li>
<li>Experiment: participants continuously adapt their extraction strategies → the <strong>present time may be more relevant for discounting</strong>.</li>
</ul>
<blockquote>
<p><strong>Theory suggests no difference</strong> in optimal behavior based on the discounting reference period. However, <strong>if subjects revise their extraction plans</strong>, discounting period reference may influence decisions.</p>
</blockquote>
</section>
<section class="slide level2">

<ul>
<li>We compare two discounting methods in a continuous-time resource extraction game:
<ul>
<li><strong>z-Discounting</strong>: Gains are discounted at the initial time (time zero).</li>
<li><strong>p-Discounting</strong>: Gains are discounted at the current time (present time).</li>
</ul></li>
<li>Both methods yield the same theoretical optimal extraction path.</li>
<li>However, they lead to different <strong>perceived gains</strong> at any given time, which may influence behavior.</li>
</ul>
<p><em>Note: in both cases we implement infinite horizon with the scrap value method, i.e.&nbsp;the future discounted gains are calculated assuming a constant extraction rate equal to the last extraction rate.</em></p>
</section>
<section class="slide level2">

<h3 id="difference-between-z-discounting-and-p-discounting-gains">Difference Between z-Discounting and p-Discounting Gains</h3>
<p>For a given payoff function <span class="math inline">\(G(E_t, R_t)\)</span>, where <span class="math inline">\(E_t\)</span> is the extraction rate and <span class="math inline">\(R_t\)</span> is the resource stock at time <span class="math inline">\(t\)</span>, the total discounted gains are calculated as follows (with <span class="math inline">\(\rho\)</span> the discount rate):</p>
<p><strong>z-Discounting</strong>: All payoffs are valued relative to the initial starting time <span class="math inline">\(t=0\)</span>: <span class="math display">\[
GP_p^Z = \int_{t=0}^p e^{-\rho t} G(E_t, R_t) \, dt + \int_{t &gt; p}^\infty e^{-\rho t} G(E_t, R_t) \, dt
\]</span></p>
<p><strong>p-Discounting</strong>: All payoffs are evaluated based on their value at <span class="math inline">\(p\)</span>, regardless of the starting point: <span class="math display">\[
GP_p^P = \int_{t=0}^p e^{\rho (p - t)} G(E_t, R_t) \, dt + \int_{t &gt; p}^\infty e^{-\rho (t - p)} G(E_t, R_t) \, dt
\]</span></p>
</section>
<section class="slide level2">

<p><strong>Relationship Between z-Discounting and p-Discounting</strong>: - <strong>Conversion Factor</strong>: <span class="math inline">\(GP_p^P = GP_p^Z \times e^{\rho p}\)</span> - This factor <span class="math inline">\(e^{\rho p}\)</span> scales the p-discounted gains relative to the z-discounted gains.</p>
<blockquote>
<p>While both discounting methods aim to model long-term value, the choice of reference point (initial time vs.&nbsp;present time) affects perceived gain magnitude. This shift can <strong>influence behavior</strong>, especially in dynamic settings, as players may respond differently to nominally larger or smaller gains.</p>
</blockquote>
</section>
<section class="slide level2">

<h3 id="experimental-design-2">Experimental design</h3>
<ul>
<li>A continuous-time resource extraction game.</li>
<li>Two parts : optimal control (single player) and game (2 players interaction). (<em>only optimal control analyzed in the paper</em>)</li>
<li>Between-subject design</li>
<li>Two treatments:
<ul>
<li><strong>z-discounting</strong>: Gains discounted at time zero. 90 participants.</li>
<li><strong>p-discounting</strong>: Gains discounted at the current time. 70 participants</li>
</ul></li>
<li>Feedback is provided on resource levels, extractions, and gains.</li>
<li>5 minutes of play (300 secondes)</li>
<li>Control tasks: Convex Time Budget (CTB, impatience), Bomb Risk Elicitation Task (BRET, risk tolerance)</li>
</ul>
</section>
<section class="slide level2">

<h3 id="results-3">Results</h3>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/discounting/extraction_ressource.png" height="500"></p>
<figcaption>Evolution</figcaption>
</figure>
</div>
</section>
<section class="slide level2">

<ul>
<li><strong>Extraction rates</strong>: <em>Higher under p-discounting</em> compared to z-discounting. Significant deviation from the optimal extraction path in p-discounting.</li>
<li><strong>Resource depletion</strong>: <em>Faster depletion in p-discounting</em>. Suboptimal behavior compared to z-discounting.</li>
</ul>
<p><strong>Other observations</strong>: - Subjects who followed optimal strategies showed no treatment effect. - Non-optimal subjects extracted more under p-discounting.</p>
</section>
<section class="slide level2">

<h3 id="findings-and-implications-3">Findings and implications</h3>
<ul>
<li>Contrary to theory, discounting reference periods affect behavior.</li>
<li>Behavior is influenced by <strong>perceived gains</strong> rather than rational planning.</li>
<li>Suggest reliance on z-discounting for better alignment with theoretical predictions.</li>
</ul>
</section>
<section id="individual-and-strategic-behaviors" class="slide level2">
<h2>Individual and strategic behaviors</h2>
<p>Djiguemde, M. Dubois, D. Sauquet, A. &amp; Tidball, M., 2022. <a href="https://doi.org/10.1080/00036846.2022.2129576">Individual and strategic behaviors in a dynamic extraction problem: results from a within-subject experiment in continuous time</a>. Applied Economics, pp.&nbsp;1-24.</p>
</section>
<section class="slide level2">

<h3 id="research-questions">Research questions</h3>
<ul>
<li>Do experimental subjects behave as predicted by the dynamic continuous-time model ?</li>
<li>What is the impact of strategic interactions in the dynamic context ?</li>
</ul>
<blockquote>
<p>We compare the observations to the theoretical behaviors, in a single agent situation (optimal control problem) and in a two-players game (differential game).</p>
</blockquote>
</section>
<section class="slide level2">

<h3 id="theoretical-paths-1">Theoretical Paths</h3>
<p><strong>Optimal control problem (single player):</strong> - The <strong>optimal behaviour</strong> is when the player chooses their extraction to maximize their discounted net payoffs and maintain the resource at an efficient level over time. - The <strong>myopic solution</strong> is when the player only seeks to maximize their current payoff, without considering the future evolution of the resource.</p>
</section>
<section class="slide level2">

<p><strong>Game (multiple players):</strong> - The <strong>social optimum</strong> (cooperative solution) is when all players coordinate to maximize the joint discounted net payoffs, maintaining the resource at an efficient level for the group. - The <strong>feedback equilibrium</strong> is when each player maximizes their own discounted net payoffs, adopting a non-cooperative strategy and taking into account the evolution of the resource. - The <strong>myopic solution</strong> remains: each player maximizes only their current payoff, ignoring future consequences.</p>
</section>
<section class="slide level2">

<p><em>Theoretical Paths in the game</em> <img data-src="img/profiles/theoretical_paths.png" class="quarto-figure quarto-figure-center" height="500" alt="Theoretical Paths"></p>
</section>
<section class="slide level2">

<h3 id="experimental-design-3">Experimental design</h3>
<ul>
<li>Continuous-time resource extraction game, discretization rate <span class="math inline">\(\tau=1\)</span> (i.e.&nbsp;1 second = 1 instant).</li>
<li>Two scenarios: optimal control (single player) and game (2 players).</li>
<li>Within-subject design: each participant played both scenarios.</li>
<li>2 trials round for each scenario before playing for money (learning phase).</li>
<li>5 minutes of play (300 seconds).</li>
<li>70 participants.</li>
</ul>
</section>
<section class="slide level2">

<h3 id="results-4">Results</h3>
<p><strong>Evolution of the resource level</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/profiles/resource_both_treatment.png" height="350"></p>
<figcaption>Av. resource in both treatments</figcaption>
</figure>
</div>
<ul>
<li>Over-exploitation at the beginning (higher in the game).</li>
<li>Greater dispersion observed in the game.</li>
</ul>
</section>
<section class="slide level2">

<p><strong>Player Behavior Profiles</strong></p>
<ul>
<li>We analyzed whether individuals and groups exhibited <strong>myopic, feedback, or optimal behavior</strong>.</li>
<li>This was based on the <strong>Mean Squared</strong> between the observed path and the theoretical one.</li>
<li>We <strong>classified players/groups</strong> as “significantly” optimal, myopic, feedback, or undetermined based on their MSDs.</li>
</ul>
<p><em>We also considered the conditional MSD (with respect to the <span class="math inline">\(t - 1\)</span> resource level) and applied regressions to check that the coefficient of the conditional decisions corresponding to the lowest MSD was actually different from zero.</em></p>
</section>
<section class="slide level2">

<p><strong>Optimal control problem</strong></p>
<ul>
<li>27.14% of participants exhibited <em>optimal behavior</em>, while 72.86% were <em>undetermined</em>.</li>
<li>Upon visual inspection of the undetermined profiles, we defined new profiles: <em>convergent</em> (21.43%) and <em>under-exploiter</em> (24.29%)</li>
<li>27.14% remained <em>without any particular pattern</em></li>
</ul>
</section>
<section class="slide level2">

<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/profiles/control_profiles.png" height="500"></p>
<figcaption>Control Profiles</figcaption>
</figure>
</div>
</section>
<section class="slide level2">

<p><strong>Game</strong></p>
<ul>
<li>20% of groups exhibited <em>optimal behavior</em>, while 80% were <em>undetermined</em></li>
<li>Upon visual inspection of the undetermined profiles, we defined new profiles : <em>convergent</em> (25.71%), <em>under-exploiter</em> (14.29%) and <em>over-exploiter</em> (17.14%)</li>
<li>22.86% remained <em>without any particular pattern</em></li>
</ul>
</section>
<section class="slide level2">

<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/profiles/game_profiles.png" height="500"></p>
<figcaption>Game Profiles</figcaption>
</figure>
</div>
</section>
<section class="slide level2">

<p><strong>Group Composition and Game Outcome</strong></p>
<ul>
<li>The composition of groups, in terms of the profiles identified in the optimal control scenario, significantly impacts the outcome of the game.</li>
<li>Groups composed of players who exhibited optimal or convergent behavior in the optimal control scenario tend to perform better in the game scenario: they are more likely to coordinate their actions and achieve higher collective payoffs.</li>
</ul>
</section>
<section class="slide level2">

<h3 id="findings-and-implications-4">Findings and implications</h3>
<ul>
<li>As expected, <strong>strategic interaction increases the tragedy of the common</strong>.</li>
<li>Nearly 20-25% of individuals and groups succeed in playing <strong>significantly optimal</strong>.</li>
<li>Another 20-25% play optimally but over a finite horizon, the category we called <strong>convergent</strong>.</li>
<li>Our findings underscore the importance of <strong>educating players</strong> about optimal strategies in dynamic resource management contexts.</li>
</ul>
</section>
<section class="slide level2">

<ul>
<li>When players understand how to manage resources optimally over an infinite horizon in a <strong>single-player scenario</strong>, they are better equipped to handle the complexities introduced by strategic interactions in a <strong>multi-player scenario</strong>.</li>
<li>Therefore, efforts to improve individual understanding and decision-making in dynamic resource management can have significant positive impacts on collective outcomes when strategic interactions are involved.</li>
</ul>
</section>
<section id="related-ongoing-research-projects" class="slide level2">
<h2>Related ongoing research projects</h2>
<p><em>Davin, M., Dubois, D., Erdlenbruch, K. &amp; Willinger, M.</em></p>
<p><strong>Threshold Effects in Resource Management</strong> - Examining the impact of an exogenous depletion threshold on resource sustainability. If the resource stock falls below this threshold, it will not renew, making extraction impossible.</p>
<p><strong>Impact of Predetermined Shocks on Resource Growth</strong> - Studying the effects of a shock at a fixed or random date on resource availability. The shock reduces resource growth, simulating environmental changes like reduced rainfall.</p>
</section></section>
<section>
<section id="intergenerational-management-of-common-pool-resources" class="title-slide slide level1 center">
<h1>Intergenerational Management of Common Pool Resources</h1>

</section>
<section class="slide level2">

<ul>
<li>Climate change, biodiversity loss, and resource depletion depend on today’s decisions.</li>
<li>Overexploitation of renewable resources threatens future welfare.</li>
<li>Future generations have no agency: they cannot reciprocate, vote, or punish.<br>
</li>
<li>Cooperation with the future is a special kind of social dilemma.</li>
</ul>
</section>
<section id="the-intergenerational-goods-game-igg" class="slide level2">
<h2>The Intergenerational Goods Game (IGG)</h2>
<p><em>Hauser, Rand, Peysakhovich, Nowak (2014, Nature)</em></p>
<ul>
<li>Successive generations of 5 players share a common pool of 100 units.</li>
<li>Each player can extract 0–20 units.</li>
<li>If total extraction ≤ threshold T = 50%, the pool renews to 100 units.<br>
</li>
<li>If extraction &gt; T, the resource collapses → all future generations get 0.</li>
<li>The game continues with probability <span class="math inline">\(δ = 0.8\)</span> (≈ 5 generations expected).</li>
</ul>
<blockquote>
<p><strong>Social optimum:</strong> 10 units per player<br>
<strong>Individual temptation:</strong> 20 units</p>
</blockquote>
</section>
<section class="slide level2">

<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/generation/hauser_igg.png" height="500"></p>
<figcaption>Hauser et al.&nbsp;IGG</figcaption>
</figure>
</div>
</section>
<section id="intragenerational-conflict-undermines-cooperation-with-the-future" class="slide level2">
<h2>Intragenerational conflict undermines cooperation with the future</h2>
<p><em>Bayle, G., Pinçon, V., Barragan-Jason, G., Bazart, C., Ibanez, L., Roussel, S., Syssau-Vaccarella, A., Dubois, D., Willinger, M.</em></p>
</section>
<section class="slide level2">

<h3 id="research-question-4">Research Question</h3>
<p><strong><em>Does intragenerational conflict undermine cooperation with the future?</em></strong></p>
<p>We disentangle: - Intergenerational dilemma: present vs.&nbsp;future.<br>
- Intragenerational dilemma: conflict among current individuals.</p>
</section>
<section class="slide level2">

<h3 id="adapted-igg">Adapted IGG</h3>
<ul>
<li>Two treatments:
<ul>
<li><strong>1P</strong>: one player extracts 0–60 units (intergenerational dilemma only).</li>
<li><strong>3P</strong>: three players extract 0–20 units each (inter + intragenerational dilemmas).</li>
</ul></li>
<li>Renewal threshold T = 30 units (≤ 50 % of the resource).</li>
<li>If extraction &gt; T → resource collapses → all future payoffs = 0.</li>
<li>No probabilistic continuation (5 generations fixed).</li>
</ul>
</section>
<section class="slide level2">

<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/generation/game.png" class="quarto-figure quarto-figure-center" height="500"></p>
</figure>
</div>
</section>
<section class="slide level2">

<h3 id="hypotheses">Hypotheses</h3>
<ol type="1">
<li><strong>H1:</strong> Cooperation is higher when no intragenerational conflict exists (1P &gt; 3P).<br>
</li>
<li><strong>H2:</strong> Intragenerational conflict reduces sustainability via coordination failures.</li>
</ol>
</section>
<section class="slide level2">

<h3 id="data-collection">Data collection</h3>
<ul>
<li>During the 2024 <em>Nuits des chercheurs</em> and the 2024 <em>Fête de la Science</em> (Montpellier).</li>
<li>Participants were students and general public.</li>
<li>Experiment implemented on tablets.</li>
<li>5 generations (not <span class="math inline">\(\delta\)</span>-probabilistic).</li>
<li>No interaction between participants, they arrived sequentially → strategy method : participants took decisions for generation 1, generations 2–4, and generation 5 (no future value).</li>
<li>Generations constituted ex post, after data collection.</li>
<li>Participants were paid according to their extraction decisions, by bank transfer.</li>
</ul>
</section>
<section class="slide level2">

<h3 id="results-5">Results</h3>
<p>260 participants (137 in <em>1P</em> and 123 in <em>3P</em>).</p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/generation/intra_inter_extractions.png" class="quarto-figure quarto-figure-center" height="450"></p>
</figure>
</div>
</section>
<section class="slide level2">

<h4 id="cooperation-rates">Cooperation rates</h4>
<p><em>Cooperation = 1 if extraction ≤ 30 units (renewal threshold), 0 otherwise.</em></p>
<ul>
<li>1P: 97–96 %.<br>
</li>
<li>3P: 70–76 %.</li>
</ul>
<p>⇒ With contemporaries, cooperation collapses.</p>
<h4 id="extraction-distributions">Extraction Distributions</h4>
<ul>
<li>1P: concentrated around the 50 % threshold.<br>
</li>
<li>3P: wider variance, with both over- and under-extractors.</li>
</ul>
</section>
<section class="slide level2">

<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>Cooperation</th>
<th>Extraction (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1P × Gen 1 (réf.)</td>
<td>12.702<span class="math inline">\(^{***}\)</span></td>
<td>0.412<span class="math inline">\(^{***}\)</span></td>
</tr>
<tr class="even">
<td>3P vs 1P</td>
<td>-4.566<span class="math inline">\(^{*}\)</span></td>
<td>0.113<span class="math inline">\(^{***}\)</span></td>
</tr>
<tr class="odd">
<td>Gen 2–4 vs Gen 1</td>
<td>-1.840</td>
<td>-0.039<span class="math inline">\(^{***}\)</span></td>
</tr>
<tr class="even">
<td>Interaction (3P × Gen 2–4)</td>
<td>4.688<span class="math inline">\(^{*}\)</span></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Num. Obs.</td>
<td>520</td>
<td>520</td>
</tr>
</tbody>
</table>
<p><em>Note</em>: <span class="math inline">\(^*\)</span> p &lt; 0.05, <span class="math inline">\(^{**}\)</span> p &lt; 0.01, <span class="math inline">\(^{***}\)</span> p &lt; 0.001</p>
</section>
<section class="slide level2">

<h4 id="resource-sustainability">Resource sustainability</h4>
<p><em>Monte Carlo (10 000 trajectories)</em> to estimate the <strong>expected survival of the resource</strong> over five generations.</p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/generation/simulations_process.png" height="425"></p>
<figcaption>Monte Carlo Simulations</figcaption>
</figure>
</div>
</section>
<section class="slide level2">

<ol type="1">
<li>Draw decisions : Use individual extraction decisions from the experiment (1P or 3P).</li>
<li>Random generation assembly : Randomly draw participants <em>without replacement</em> to form each generation (1 or 3 players). Each trajectory = 5 successive generations.</li>
<li>Renewal rule:
<ul>
<li>Resource renews if total extraction ≤ 30 units.</li>
<li>If extraction &gt; 30 → resource collapses → all future payoffs = 0.</li>
</ul></li>
<li>Iteration: Repeat the process 10,000 times to simulate variability in group composition and decisions.</li>
<li>Output: Compute the proportion of surviving trajectories at each generation.</li>
</ol>
</section>
<section class="slide level2">

<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/generation/intra_inter_survivals.png" class="quarto-figure quarto-figure-center" height="500"></p>
</figure>
</div>
<p>⇒ <strong>Intragenerational conflict drastically reduces resource sustainability</strong>.</p>
</section>
<section class="slide level2">

<h3 id="findings-and-implications-5">Findings and implications</h3>
<ul>
<li>Intragenerational conflict sharply reduces cooperation and resource sustainability, as shown by lower survival rates of the resource when present.</li>
<li>Effective climate and resource governance must tackle both intra- and intergenerational dilemmas: coordination among contemporaries is as important as concern for future generations.</li>
<li>Addressing these challenges requires a dual strategy:
<ul>
<li><em>Structural mechanisms</em> (institutions, monitoring) to reduce present-day coordination failures.</li>
<li><em>Normative interventions</em> (future-oriented design, education) to foster long-term sustainability.</li>
</ul></li>
</ul>
</section>
<section id="legacy-or-lineage-framing-the-future-for-sustainability" class="slide level2">
<h2>Legacy or Lineage? Framing the Future for sustainability</h2>
<p><em>Barragan-Jason, G., Bayle, G., Bazart, C., Dubois, D., Ibanez, L., Pinçon, V., Roussel, S., Syssau-Vaccarella, A., Willinger, M.</em></p>
</section>
<section id="research-question-5" class="slide level2">
<h2>Research Question</h2>
<p><strong><em>Can behavioral framings (primings / nudges) restore concern for the future?</em></strong></p>
</section>
<section id="conceptual-distinctions" class="slide level2">
<h2>Conceptual distinctions</h2>
<p><strong>Priming</strong>: subtle activation of concepts, norms, or emotions that influence later behavior (Bargh 1994, Bargh et al.&nbsp;1996, Bargh &amp; Chartrand 2000).</p>
<p><strong>Framing</strong>: explicit presentation of information that shapes how individuals interpret and respond to a choice (Tversky &amp; Kahneman 1981, Levin et al.&nbsp;1998).</p>
<p><strong>Nudges</strong>: subtle changes in the choice architecture that alter behavior without forbidding options (Thaler &amp; Sunstein, 2008).</p>
</section>
<section class="slide level2">

<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 4%">
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong>Priming</strong></th>
<th><strong>Framing</strong></th>
<th><strong>Nudge</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Definition</strong></td>
<td>Implicit activation of concepts or norms</td>
<td>Explicit presentation shaping interpretation of a choice</td>
<td>Contextual modification steering behavior without constraint</td>
</tr>
<tr class="even">
<td><strong>Cognitive level</strong></td>
<td>Mostly unconscious</td>
<td>Conscious interpretation</td>
<td>Conscious / semi-conscious</td>
</tr>
<tr class="odd">
<td><strong>Focus</strong></td>
<td>Perception &amp; associations</td>
<td>Meaning &amp; perspective</td>
<td>Actual choice behavior</td>
</tr>
</tbody>
</table>
</section>
<section class="slide level2">

<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 5%">
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong>Priming</strong></th>
<th><strong>Framing</strong></th>
<th><strong>Nudge</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Example</strong></td>
<td>Reading “future generations” primes prosocial thinking</td>
<td>Framing extraction as “for 2100” or “for your descendants”</td>
<td>Changing default extraction or payoff display</td>
</tr>
<tr class="even">
<td><strong>Discipline</strong></td>
<td>Cognitive psychology</td>
<td>Cognitive + behavioral economics</td>
<td>Behavioral public policy</td>
</tr>
</tbody>
</table>
<blockquote>
<p>Framing acts as a <strong>bridge</strong> between priming and nudging:<br>
it shapes <em>how people think about the choice</em> rather than <em>what choices they face.</em></p>
</blockquote>
</section>
<section class="slide level2">

<h3 id="four-treatments-all-in-3p-igg">Four Treatments (all in 3P IGG)</h3>
<p><strong><em>Different Framing messages</em></strong></p>
<p><strong>Common message (all treatments):</strong> (on the decision screen)</p>
<blockquote>
<p>Common resources, such as fish stocks or forests, are renewable — but they can be depleted if not managed sustainably. When we extract too much, these resources cannot regenerate and may disappear permanently.</p>
</blockquote>
<p><strong>Control</strong>: No additional message.</p>
<p><strong>Near future</strong> and <strong>Close kin</strong> &gt; Adopting responsible practices helps preserve these valuable resources for &gt; — Future generations (up to 2100) &gt; — Your close descendants (up to 2100)</p>
</section>
<section class="slide level2">

<p><strong>Self-projection treatment</strong> (screen before decision screen)</p>
<p>Before making their extraction decision, participants were asked to imagine themselves as members of the next generation:</p>
<blockquote>
<p>“If you belonged to the next generation, what amount of the resource would you want your generation to extract?”</p>
</blockquote>
<p>They were reminded that they did not know their actual generation (1, 2, 3, 4, or 5), the goal was to mentally adopt the perspective of those who will face the consequences.</p>
</section>
<section class="slide level2">

<h3 id="hypotheses-1">Hypotheses</h3>
<ol type="1">
<li><strong>H1:</strong> Framing the future (Near future, Close kin) increases cooperation compared to Control.<br>
</li>
<li><strong>H2:</strong> Self-projection enhances cooperation by fostering empathy with future generations.</li>
</ol>
<p>Close kin &gt; Near future &gt; Control<br>
Self-projection &gt; Control<br>
Future framing ? self-projection</p>
</section>
<section class="slide level2">

<h3 id="data-collection-1">Data collection</h3>
<ul>
<li>During the 2024 <em>Nuits des chercheurs</em> and the 2024 <em>Fête de la Science</em> (Montpellier).</li>
<li>Participants were students and general public.</li>
<li>Experiment implemented on tablets.</li>
<li>5 generations (not <span class="math inline">\(\delta\)</span>-probabilistic).</li>
<li>No interaction between participants, they arrived sequentially → strategy method : participants took decisions for generation 1, generations 2–4, and generation 5 (no future value).</li>
<li>Generations constituted ex post, after data collection.</li>
<li>Participants were paid according to their extraction decisions, by bank transfer.</li>
</ul>
</section>
<section class="slide level2">

<h3 id="results-6">Results</h3>
<p><em>371 participants (123 in Control, 68 in Near future, 69 in Close kin, 111 in Self-projection).</em></p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/generation/framing_extractions.png" height="425"></p>
<figcaption>Extractions by treatment</figcaption>
</figure>
</div>
</section>
<section class="slide level2">

<table class="caption-top">
<thead>
<tr class="header">
<th>Num. Obs. 742 — (371 × 2)</th>
<th>Cooperation</th>
<th>Extraction (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>No nudge (Gen 1)</td>
<td>0.843<span class="math inline">\(^{***}\)</span></td>
<td>0.532<span class="math inline">\(^{***}\)</span></td>
</tr>
<tr class="even">
<td>Self projection (Gen 1)</td>
<td>0.392</td>
<td>–0.002</td>
</tr>
<tr class="odd">
<td>Close kin (Gen 1)</td>
<td>–0.017</td>
<td>–0.012</td>
</tr>
<tr class="even">
<td>Near future (Gen 1)</td>
<td>0.697<span class="math inline">\(^{+}\)</span></td>
<td>–0.071<span class="math inline">\(^{*}\)</span></td>
</tr>
<tr class="odd">
<td>No nudge (Gen 2–4)</td>
<td>0.333</td>
<td>–0.054<span class="math inline">\(^{**}\)</span></td>
</tr>
<tr class="even">
<td>Self projection (Gen 2–4)</td>
<td>0.009</td>
<td>0.002</td>
</tr>
<tr class="odd">
<td>Close kin (Gen 2–4)</td>
<td>0.503</td>
<td>–0.026</td>
</tr>
<tr class="even">
<td>Near future (Gen 2–4)</td>
<td>–0.115</td>
<td>0.023</td>
</tr>
</tbody>
</table>
<p><em>Note</em>: <span class="math inline">\(^+\)</span> p &lt; 0.1, <span class="math inline">\(^{*}\)</span> p &lt; 0.05, <span class="math inline">\(^{**}\)</span> p &lt; 0.01, <span class="math inline">\(^{***}\)</span> p &lt; 0.001</p>
</section>
<section class="slide level2">

<p><em>Monte Carlo (10 000 trajectories)</em>.</p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/generation/framing_survivals.png" height="500"></p>
<figcaption>Survivals</figcaption>
</figure>
</div>
</section>
<section class="slide level2">

<h3 id="findings-and-implications-6">Findings and implications</h3>
<ul>
<li>Framing the future as benefiting the “near future” (up to 2100) significantly increases cooperation and resource sustainability.</li>
<li>Framing the future as benefiting “close kin” does not significantly affect cooperation compared to the control.</li>
<li>Self-projection does not significantly enhance cooperation compared to the control.</li>
<li>Effective communication strategies should emphasize the tangible benefits of sustainable practices for the near future to foster cooperation and long-term resource sustainability.</li>
<li>Future research should explore additional framings and interventions to further enhance cooperation with future generations.</li>
</ul>
</section></section>
<section>
<section id="dynamic-common-pool-resource-with-spatial-externalities" class="title-slide slide level1 center">
<h1>Dynamic Common Pool Resource with Spatial Externalities</h1>

</section>
<section id="mobile-resources" class="slide level2">
<h2>Mobile resources</h2>
<ul>
<li><strong>Fisheries</strong>: Fish stocks move between fishing zones. Management involves spatial externalities, as exploitation in one area can affect stock availability in others. (Costello &amp; Polasky 2008; Sanchirico &amp; Wilen 1999)</li>
<li><strong>Transboundary Aquifers</strong>: Groundwater aquifers span multiple jurisdictions. Pumping in one region affects water availability in connected regions. (Brozovic, Sunding, &amp; Zilberman 2010; Pfeiffer &amp; Lin 2012)</li>
<li><strong>Communal Pastures</strong>: Shared grazing lands are used by multiple herders. Overgrazing in one area can degrade resources and affect neighboring areas due to herd mobility. (Ostrom 1990)</li>
</ul>
</section>
<section class="slide level2">

<ul>
<li><strong>Transboundary Forests</strong>: Forests span multiple jurisdictions, and logging in one area can affect neighboring areas, particularly concerning biodiversity and ecosystem services. (Albers &amp; Robinson 2013).</li>
<li><strong>Pollination and Ecosystem Services</strong>: Pollinators (like bees) move between crop fields, and managing pollination habitats in one area can affect agricultural productivity in neighboring areas. (Ricketts et al.&nbsp;2008)</li>
</ul>
</section>
<section id="theoretical-benchmark" class="slide level2">
<h2>Theoretical Benchmark</h2>
<p><em>Based on Costello et al.&nbsp;(2015)</em></p>
<ul>
<li><strong>Discrete Spatial Domain</strong>: <span class="math inline">\(N\)</span> patches, each managed independently but interlinked through resource mobility.</li>
<li><strong>Discrete Time Model</strong>: The state of the resource and management actions are updated period by period.</li>
</ul>
</section>
<section class="slide level2">

<ul>
<li><strong>Resource Growth Dynamics</strong>: Growth function <span class="math inline">\(g(e,\alpha)\)</span> depends on the escapement <span class="math inline">\(e\)</span> (residual stock) and growth parameters <span class="math inline">\(\alpha\)</span>.</li>
<li><strong>Mobility Matrix</strong>: <span class="math inline">\(D_{ij}\)</span> defines the fraction of resources moving from patch <span class="math inline">\(i\)</span> to patch <span class="math inline">\(j\)</span>, capturing the spatial dynamics of resource movement. <span class="math inline">\(D_{ii}\)</span> refers to the retention rate.</li>
<li><strong>Profit Function</strong>: <span class="math inline">\(\pi_{it}=p_i \times h_{it}\)</span>, where <span class="math inline">\(p_i\)</span> is the price of the resource in patch <span class="math inline">\(i\)</span> and <span class="math inline">\(h_{it}\)</span> is the harvested amount at time <span class="math inline">\(t\)</span>.</li>
</ul>
</section>
<section class="slide level2">

<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/spatial/illustration_model.png" height="500"></p>
<figcaption>Model illustration</figcaption>
</figure>
</div>
</section>
<section class="slide level2">

<p><em>Flow of resources between two patches</em></p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/spatial/illustration_jeu.png" height="500"></p>
<figcaption>Game Illustration</figcaption>
</figure>
</div>
</section>
<section class="slide level2">

<p><em>Screenshot</em></p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/spatial/illustration_experiment.png" height="500"></p>
<figcaption>Experiment Illustration</figcaption>
</figure>
</div>
</section>
<section id="spatial-externalities-and-collective-action" class="slide level2">
<h2>Spatial Externalities and Collective Action</h2>
<p><em>Bayle, G., Dubois, D., Beaud, M., Willinger, M. &amp; Querou, N.</em>.</p>
</section>
<section class="slide level2">

<h3 id="research-questions-1">Research questions</h3>
<ul>
<li>How spatial externalities affect the efficiency of resource management.</li>
<li>Which management structures (single vs.&nbsp;multiple actors) lead to better resource sustainability.</li>
</ul>
</section>
<section class="slide level2">

<h3 id="theoretical-predictions">Theoretical predictions</h3>
<ul>
<li><p><strong>Efficient path</strong>: Maximizes the aggregate payoffs in both patches over the entire time horizon ⇒ Since <span class="math inline">\(\alpha &gt; 0\)</span> the resource is conserved in both patches (zero harvest) up until the last period and entirely extracted in the last period.</p></li>
<li><p><strong>Decentralized (non cooperative) solution</strong>: The subgame perfect Nash equilibrium (SPNE) depends on the marginal productivity of the patch and the number of players managing the patch</p></li>
</ul>
</section>
<section class="slide level2">

<p><strong>Patch marginal productivity</strong>: retention rate × growth factor → <span class="math inline">\(D_{ii} \times (1 + \alpha)\)</span></p>
<ul>
<li>If <span class="math inline">\(D_{ii} \times (1 + \alpha)&lt;1\)</span> —<strong>low marginal productivity</strong>— the resource is mined in both patches initially.</li>
<li>If <span class="math inline">\(D_{ii} \times (1 + \alpha)&lt;2\)</span> —<strong>high marginal productivity</strong>— the number of players affects equilibrium harvests.
<ul>
<li>With <strong>one player per patch</strong> (1A-1B), the SPNE path matches the efficient path.</li>
<li>With <strong>two players in patch B</strong> (1A-2B), B players mine continuously, while the A players leaves the resource until the final period, then harvests all remaining stock.</li>
</ul></li>
</ul>
</section>
<section class="slide level2">

<h3 id="hypotheses-2">Hypotheses</h3>
<ul>
<li><p>H1 : <strong>Higher resource mobility decreases overall management efficiency</strong> and increases the likelihood of over-exploitation.<br>
<em>High resource mobility implies low marginal productivity for the patch.</em></p></li>
<li><p>H2 : <strong>Single manager systems are more efficient and sustainable</strong> compared to multiple manager systems.<br>
<em>If 2 players in patch B, even in case of a high marginal productivity they mine the resource in their patch.</em></p></li>
</ul>
</section>
<section class="slide level2">

<h3 id="experimental-design-and-parameters">Experimental design and parameters</h3>
<ul>
<li>Lab experiment</li>
<li>2 treatments:
<ul>
<li>1A-1B : one player in patch A and one player in patch B</li>
<li>1A-2B : one player in patch A and two players in patch B</li>
</ul></li>
<li>3 games per session - random rematching after each game</li>
<li>1 game = 5 periods with a constant dispersion/retention rate</li>
</ul>
</section>
<section class="slide level2">

<h3 id="game-parameters">Game parameters</h3>
<ul>
<li>Initial resource : 10 units on each patch</li>
<li>Resource growth : <span class="math inline">\(\alpha = 0.4\)</span></li>
<li>Dispersion rates: (<span class="math inline">\(D_{ij}\)</span>): 0.25, 0.50, 0.75 (→ Retention rates: 0.75, 0.50, 0.25)</li>
<li>Order of rates across games:
<ul>
<li>(0.50, 0.25, 0.75)<br>
</li>
<li>(0.25, 0.50, 0.75)<br>
</li>
<li>(0.75, 0.50, 0.25)<br>
</li>
</ul></li>
<li>Resource price: <span class="math inline">\(p_i = 1\)</span> → Each participant’s payoff for a game equals the total quantity harvested over the 5 periods.</li>
</ul>
</section>
<section class="slide level2">

<h3 id="hypotheses-with-parameters">Hypotheses with parameters</h3>
<p><em>H1 : Higher resource mobility (lower retention rate) decreases overall management efficiency and increases the likelihood of over-exploitation</em></p>
<p><strong>⇒ Total resource harvest with Dij = 0.25 &gt; Dij = 0.50 and Dij=0.75</strong></p>
<p><em>H2 : Single manager systems are more efficient and sustainable compared to multiple manager systems</em></p>
<p><strong>⇒ Total resource harvest in the single player configuration (1A-1B) &gt; (1A-2B)</strong></p>
</section>
<section class="slide level2">

<p><strong>Screenshot (1A-2B)</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="./img/spatial/screenshot.png" height="500"></p>
<figcaption>Screenshot</figcaption>
</figure>
</div>
</section>
<section class="slide level2">

<h3 id="data-collection-2">Data collection</h3>
<ul>
<li>Laboratory for Experimental Economics - Montpellier (LEEM)</li>
<li>294 participants (126 in 1A-1B and 168 in 1A-2B)</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Players per Group</th>
<th># Participants</th>
<th>Mobility Order</th>
<th># Groups</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2</td>
<td>126</td>
<td>50% - 25% - 75%</td>
<td>22</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>25% - 50% - 75%</td>
<td>21</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td>75% - 50% - 25%</td>
<td>20</td>
</tr>
<tr class="even">
<td>3</td>
<td>168</td>
<td>50% - 25% - 75%</td>
<td>18</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td>25% - 50% - 75%</td>
<td>20</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>75% - 50% - 25%</td>
<td>18</td>
</tr>
</tbody>
</table>
</section>
<section class="slide level2">

<h3 id="results-7">Results</h3>
<p><em>Higher resource mobility decreases overall management efficiency (H1) and single manager systems are more efficient than multiple manager systems (H2).</em></p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/spatial/extraction.png" height="430"></p>
<figcaption>Extraction</figcaption>
</figure>
</div>
</section>
<section class="slide level2">

<table class="caption-top">
<thead>
<tr class="header">
<th>Num. Obs. 357</th>
<th>Total harvest</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept (A-B1 &amp; 50%)</td>
<td>35.167***</td>
</tr>
<tr class="even">
<td>A-B2</td>
<td>-4.912**</td>
</tr>
<tr class="odd">
<td>Mobility: 25%</td>
<td>5.372**</td>
</tr>
<tr class="even">
<td>Mobility: 75%</td>
<td>-1.452</td>
</tr>
<tr class="odd">
<td>Interaction A-B2 &amp; 25%</td>
<td>-1.529</td>
</tr>
<tr class="even">
<td>Interaction A-B2 &amp; 75%</td>
<td>-2.137</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
</tr>
<tr class="even">
<td>R2</td>
<td>0.175</td>
</tr>
<tr class="odd">
<td>R2 Adj.</td>
<td>0.164</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(^+\)</span> p &lt; 0.1, <span class="math inline">\(^*\)</span> p &lt; 0.05, <span class="math inline">\(^{**}\)</span> p &lt; 0.01, <span class="math inline">\(^{***}\)</span> p &lt; 0.001</p>
</section>
<section id="findings-and-implications-7" class="slide level2">
<h2>Findings and implications</h2>
<ul>
<li>Higher resource mobility decreases management efficiency and increases over-exploitation.</li>
<li>Single manager systems are more efficient and sustainable than multiple manager systems.</li>
</ul>
<p><strong>Implications</strong> - Emphasize the importance of coordinated management practices to mitigate the negative effects of resource mobility. - Support the implementation of property rights or centralized management to enhance resource sustainability.</p>
</section>
<section id="property-rights-and-productivity" class="slide level2">
<h2>Property Rights and Productivity</h2>
<p>G. Bayle, D. Dubois, M. Beaud, M. Willinger &amp; N. Quérou</p>
</section>
<section class="slide level2">

<h3 id="research-question-6">Research question</h3>
<p><strong><em>How should exclusive vs.&nbsp;shared property rights be allocated in environments with heterogeneous resource productivity?</em></strong></p>
</section>
<section class="slide level2">

<h3 id="property-rights-and-productivity-allocation">Property Rights and Productivity Allocation</h3>
<p>The property regime is defined by the number of players per patch: - 1 player (patch A) → Exclusive rights - 2 players (patch B) → Shared rights</p>
<p>Location of high productivity: - <em><span class="math inline">\(A_h\)</span></em>: high productivity in <em>exclusive</em> patch (A) - <em><span class="math inline">\(B_h\)</span></em>: high productivity in <em>shared</em> patch (B)</p>
<p><strong>⇒ Do productive zones perform better under </strong>exclusive or shared** management?**</p>
</section>
<section class="slide level2">

<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/spatial/illustration_jeu_cra3.png" height="500"></p>
<figcaption>Game illustration</figcaption>
</figure>
</div>
</section>
<section class="slide level2">

<h3 id="efficient-vs.-strategic-extraction">Efficient vs.&nbsp;Strategic Extraction</h3>
<ul>
<li><p><strong>Efficient path</strong>: maximizes total payoff over time Players should let the resource grow and harvest everything in the last period ⇒ No extraction in <span class="math inline">\(t &lt; T\)</span>, full harvest in <span class="math inline">\(t = T\)</span></p></li>
<li><p><strong>Decentralized (non-cooperative) behavior</strong>: Players anticipate others’ overharvesting ⇒ early and excessive extraction to preempt rivals and secure payoffs</p></li>
</ul>
</section>
<section class="slide level2">

<h3 id="impact-of-productivity-allocation">Impact of Productivity Allocation</h3>
<ul>
<li><p>When <em>high productivity is managed by a single player</em>, the player can afford to be patient → behavior close to the efficient path</p></li>
<li><p>When <em>high productivity is managed by two players</em>, they may rush to extract early to outcompete each other → behavior deviates from the efficient path, leading to over-extraction. This externality affects the other patch through resource mobility.</p></li>
</ul>
</section>
<section class="slide level2">

<h3 id="predicted-outcome">Predicted outcome</h3>
<table class="caption-top">
<thead>
<tr class="header">
<th>Treatment</th>
<th>Behavior in high-prod. patch</th>
<th>Efficiency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(A_h\)</span> (exclusive)</td>
<td>Conservation until <span class="math inline">\(t = T\)</span></td>
<td>Higher</td>
</tr>
<tr class="even">
<td><span class="math inline">\(B_h\)</span> (shared)</td>
<td>Early extraction</td>
<td>Lower</td>
</tr>
</tbody>
</table>
<p><strong>⇒ Exclusive rights in high-productivity areas should lead to better resource management</strong></p>
</section>
<section class="slide level2">

<h3 id="experimental-setup">Experimental Setup</h3>
<ul>
<li>Laboratory experiment</li>
<li>Between-subject design with 2 treatments:
<ul>
<li><span class="math inline">\(A_h\)</span>: high-productivity on patch A</li>
<li><span class="math inline">\(B_h\)</span>: high-productivity on patch B</li>
</ul></li>
<li>8 rounds per game</li>
<li>N = 273 participants – <span class="math inline">\(A_h\)</span>: 153, <span class="math inline">\(B_h\)</span>: 120</li>
<li>Control tasks: NLE, PGSM and GPS</li>
</ul>
</section>
<section class="slide level2">

<h3 id="game-parameters-1">Game Parameters</h3>
<ul>
<li>Initial stock: 10 units per patch</li>
<li><span class="math inline">\(D_{ii}\)</span> = 0.75 – Retention</li>
<li><span class="math inline">\(D_{ji}\)</span> = 0.25 – Dispersion</li>
</ul>
<p><em>Patch productivity = Retention × Growth factor</em></p>
<ul>
<li><span class="math inline">\((1 + \alpha)_h\)</span> = 1.6 → High productivity (<span class="math inline">\(Q=1.6 \cdot 0.75 = 1.2\)</span>)</li>
<li><span class="math inline">\((1 + \alpha)_l\)</span> = 1.1 → Low productivity (<span class="math inline">\(Q=1.1 \cdot 0.75 = 0.825\)</span>)</li>
</ul>
</section>
<section class="slide level2">

<h3 id="results-8">Results</h3>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/spatial/cumulative_harvest_stack.png" class="quarto-figure quarto-figure-center" height="450"></p>
</figure>
</div>
<p>Total harvest is <strong>higher in <span class="math inline">\(A_h\)</span> than in <span class="math inline">\(B_h\)</span></strong> – <em>Mann-Whitney test p&lt;0.05</em></p>
</section>
<section class="slide level2">

<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/spatial/cumulative_harvest_lines.png" class="quarto-figure quarto-figure-center" height="400"></p>
</figure>
</div>
<ul>
<li>Players in <strong>Patch B</strong> extract similar quantities in <span class="math inline">\(A_h\)</span> and <span class="math inline">\(B_h\)</span>– <em>MW test p=0.663</em></li>
<li>In <span class="math inline">\(B_h\)</span>, the player in <strong>Patch A</strong> extracts much less than in <span class="math inline">\(A_h\)</span> – <em>MW test p&lt;0.001</em></li>
</ul>
</section>
<section class="slide level2">

<table class="caption-top">
<thead>
<tr class="header">
<th>Num. Obs. 1456</th>
<th>Harvest</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Patch A x Ah</td>
<td>2.849***</td>
</tr>
<tr class="even">
<td>Patch A x Bh</td>
<td>-1.674***</td>
</tr>
<tr class="odd">
<td>Patch B x Ah</td>
<td>-0.138</td>
</tr>
<tr class="even">
<td>Patch B x Bh</td>
<td>1.311*</td>
</tr>
<tr class="odd">
<td>Round number</td>
<td>0.122+</td>
</tr>
<tr class="even">
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>R2 Marg.</td>
<td>0.013</td>
</tr>
<tr class="even">
<td>R2 Cond.</td>
<td>0.041</td>
</tr>
</tbody>
</table>
</section>
<section class="slide level2">

<p>Compared to Patch A x <span class="math inline">\(A_h\)</span> (ref.): - <strong>Patch A x <span class="math inline">\(B_h\)</span></strong>: −1.67 units (p &lt; 0.001) → Lower harvest in Patch A when high productivity moves to patch B - <strong>Patch B x <span class="math inline">\(B_h\)</span></strong>: +1.31 units (p = 0.037) → Negative effect of the high productivity on patch B (<span class="math inline">\(B_h\)</span>) is mitigated in Patch B (-1.67 + 1.31 = -0.36)</p>
<p>⇒ Assigning high productivity to Patch B (<span class="math inline">\(B_h\)</span>) significantly reduces harvest in Patch A. However, this effect is substantially moderated in Patch B, where the harvest remains nearly stable.</p>
</section>
<section class="slide level2">

<h3 id="findings-and-implications-8">Findings and implications</h3>
<ul>
<li>Exclusive rights over high-productivity areas lead to better resource conservation and higher efficiency.</li>
<li>Shared management leads to early depletion and propagates negative effects to neighboring patches via resource mobility.</li>
<li>Effective property rights design must account for both ecological productivity and strategic behavior.</li>
</ul>
</section>
<section id="ongoing-related-projects" class="slide level2">
<h2>Ongoing related projects</h2>
<ul>
<li>Introduce and study the impact of risk on the resource within the patches.</li>
<li>Explore policy interventions to mitigate over-extraction.</li>
</ul>
</section></section>
<section>
<section id="appendix-1" class="title-slide slide level1 center">
<h1>Appendix</h1>

</section>
<section id="a.-dynamic-cpr---maximization-problems" class="slide level2">
<h2>A. Dynamic CPR - Maximization Problems</h2>
<p>Two agents <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span> exploit a renewable resource <span class="math inline">\(H(t)\)</span> (e.g., groundwater).<br>
Each player’s instantaneous profit is: <span class="math display">\[
\pi_i(H, w_i) = a w_i - \frac{b}{2}w_i^2 - \max(0, c_0 - c_1 H)\, w_i
\]</span></p>
<p>The dynamics of the resource stock are: <span class="math display">\[
\dot{H}(t) = R - \alpha (w_i + w_j), \qquad H(0) = H_0,
\]</span> where <span class="math inline">\(R &gt; 0\)</span> is the natural recharge, and <span class="math inline">\(\alpha &gt; 0\)</span> the return flow coefficient.<br>
The discount rate is <span class="math inline">\(r &gt; 0\)</span>.</p>
</section>
<section class="slide level2">

<h3 id="social-optimum-1">Social Optimum</h3>
<p>The planner maximizes the joint discounted net payoffs of both players: <span class="math display">\[
\max_{\{w_i(t), w_j(t)\}_{t \ge 0}}
\int_0^{\infty} e^{-rt}
\left[
\sum_{k \in \{i,j\}}
\left( a w_k - \frac{b}{2}w_k^2 - \max(0, c_0 - c_1 H)\, w_k \right)
\right] dt
\]</span> subject to: <span class="math display">\[
\dot{H}(t) = R - \alpha (w_i + w_j)
\]</span></p>
<h4 id="hamiltonian">Hamiltonian</h4>
<p><span class="math display">\[
\mathcal{H}^S =
\sum_{k \in \{i,j\}}
\left( a w_k - \frac{b}{2}w_k^2 - \max(0, c_0 - c_1 H)\, w_k \right)
+ \lambda^S \big(R - \alpha (w_i + w_j)\big)
\]</span></p>
</section>
<section class="slide level2">

<h4 id="first-order-conditions">First-order conditions</h4>
<p><span class="math display">\[
\frac{\partial \mathcal{H}^S}{\partial w_i}
= a - b w_i - \max(0, c_0 - c_1 H) - \alpha \lambda^S = 0,
\]</span> <span class="math display">\[
\dot{\lambda}^S = r \lambda^S -
\frac{\partial \mathcal{H}^S}{\partial H}
= r \lambda^S -
\sum_{k \in \{i,j\}}
\frac{\partial}{\partial H}
\big[\max(0, c_0 - c_1 H)\, w_k \big].
\]</span></p>
<p>In symmetric equilibrium (<span class="math inline">\(w_i = w_j = w^S\)</span>): <span class="math display">\[
\dot{H} = R - 2 \alpha w^S, \qquad
a - b w^S - \max(0, c_0 - c_1 H) - \alpha \lambda^S = 0.
\]</span></p>
</section>
<section class="slide level2">

<h3 id="feedback-nash-equilibrium">Feedback Nash Equilibrium</h3>
<p>Each player <span class="math inline">\(i\)</span> maximizes his own discounted payoff, anticipating the other’s feedback rule <span class="math inline">\(w_j(H)\)</span>: <span class="math display">\[
\max_{\{w_i(t)\}_{t \ge 0}}
\int_0^{\infty} e^{-rt}
\left[a w_i - \frac{b}{2}w_i^2 - \max(0, c_0 - c_1 H)\, w_i \right] dt
\]</span> subject to: <span class="math display">\[
\dot{H} = R - \alpha (w_i + w_j(H)).
\]</span></p>
<h4 id="hamiltonian-1">Hamiltonian</h4>
<p><span class="math display">\[
\mathcal{H}_i^F =
a w_i - \frac{b}{2}w_i^2 - \max(0, c_0 - c_1 H)\, w_i
+ \lambda_i^F \big(R - \alpha (w_i + w_j(H))\big)
\]</span></p>
</section>
<section class="slide level2">

<h4 id="first-order-conditions-1">First-order conditions</h4>
<p><span class="math display">\[
\frac{\partial \mathcal{H}_i^F}{\partial w_i}
= a - b w_i - \max(0, c_0 - c_1 H) - \alpha \lambda_i^F = 0,
\]</span> <span class="math display">\[
\dot{\lambda}_i^F = r \lambda_i^F -
\frac{\partial \mathcal{H}_i^F}{\partial H}
= r \lambda_i^F -
\frac{\partial}{\partial H}\big[\max(0, c_0 - c_1 H)\, w_i \big]
- \lambda_i^F \alpha \frac{dw_j(H)}{dH}.
\]</span></p>
<p>In symmetric equilibrium (<span class="math inline">\(w_i = w_j = w^F(H)\)</span>): <span class="math display">\[
\dot{H} = R - 2 \alpha w^F(H), \qquad
a - b w^F(H) - \max(0, c_0 - c_1 H) - \alpha \lambda^F = 0.
\]</span></p>
</section>
<section class="slide level2">

<h3 id="myopic-benchmark">Myopic Benchmark</h3>
<p>At each instant, players maximize only their payoff, taking <span class="math inline">\(H\)</span> as given.</p>
<p><span class="math display">\[
\max_{w_i \ge 0} \;
a w_i - \frac{b}{2}w_i^2 - \max(0, c_0 - c_1 H)\, w_i.
\]</span></p>
<h4 id="first-order-condition">First-order condition</h4>
<p><span class="math display">\[
a - b w_i - \max(0, c_0 - c_1 H) = 0
\quad \Rightarrow \quad
w_i^M(H) = \frac{a - \max(0, c_0 - c_1 H)}{b}, \quad w_i^M \ge 0.
\]</span></p>
<p>If <span class="math inline">\(H \ge \frac{c_0}{c_1}\)</span> (zero cost), then: <span class="math display">\[
w_i^M = \frac{a}{b}.
\]</span></p>
</section>
<section id="b.-the-exponential-function-in-discounting" class="slide level2">
<h2>B. The exponential function in discounting?</h2>
<p>The exponential function <span class="math inline">\(e^{-\rho t}\)</span> is used in continuous-time discounting because it has key mathematical and economic properties:</p>
<ul>
<li><p><strong>Stationary discounting</strong>:<br>
Its decay rate is proportional to its current value:<br>
<span class="math inline">\(\frac{d}{dt} e^{-\rho t} = -\rho e^{-\rho t}\)</span><br>
→ No memory, time-consistent discounting.</p></li>
<li><p><strong>Limit of discrete discounting</strong>:<br>
<span class="math inline">\(\lim_{n \to \infty} \left(1 + \frac{r}{n}\right)^{-nt} = e^{-rt}\)</span></p></li>
</ul>
</section>
<section class="slide level2">

<ul>
<li><p><strong>Simplifies dynamic optimization</strong>:<br>
<span class="math display">\[
\int_0^\infty e^{-\rho t} G(t) dt \quad \text{is tractable and interpretable.}
\]</span></p></li>
<li><p><strong>Avoids abrupt changes</strong>:<br>
Smooth and continuous decrease of value over time.</p></li>
</ul>
<blockquote>
<p><em>Future payoffs are worth less today, at a continuously decreasing rate.</em></p>
</blockquote>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Topics in Behavioral and Experimental Economics</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="topics_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="topics_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="topics_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="topics_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="topics_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="topics_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="topics_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="topics_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="topics_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="topics_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'bottom-right',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'h.v',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'default',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>